// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARUScYESZnYuJN2XbvKqognAnjD6n0w6c',
    appId: '1:354468388824:web:a617bcc5612e4be0455cad',
    messagingSenderId: '354468388824',
    projectId: 'liveasy-4ded4',
    authDomain: 'liveasy-4ded4.firebaseapp.com',
    storageBucket: 'liveasy-4ded4.appspot.com',
    measurementId: 'G-DJHMC48SL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAemiPAWUJQvtvA4JYM0FMbWVTDwZBUdgE',
    appId: '1:354468388824:android:7a1a92fcc9f1583c455cad',
    messagingSenderId: '354468388824',
    projectId: 'liveasy-4ded4',
    storageBucket: 'liveasy-4ded4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVpKvSmfM9lQI9Rq3_dDFc7QNqteoMprc',
    appId: '1:354468388824:ios:788614a39f523fac455cad',
    messagingSenderId: '354468388824',
    projectId: 'liveasy-4ded4',
    storageBucket: 'liveasy-4ded4.appspot.com',
    iosClientId: '354468388824-nakni9hic4c9c1a3n4m0kk6dps4j3n78.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveasyTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVpKvSmfM9lQI9Rq3_dDFc7QNqteoMprc',
    appId: '1:354468388824:ios:dad9e2abf204cb28455cad',
    messagingSenderId: '354468388824',
    projectId: 'liveasy-4ded4',
    storageBucket: 'liveasy-4ded4.appspot.com',
    iosClientId: '354468388824-t78b5pfhpcq2dutfak0rse6m6orhcl5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveasyTask.RunnerTests',
  );
}
